---
title: "'SangerAlignment' Report"
author: "Author: Kuan-Hao Chao (u7022787@anu.edu.au)"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  BiocStyle::html_document:
    toc_float: true
    fig_caption: yes
  BiocStyle::pdf_document: default
#bibliography: bibliography.bib
params:
  SangerAlignment: NULL
  outputDir: ""
  contigsFN: NULL
fontsize: 14pt
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div style="margin-left:50px; padding-left:-50;margin-top:50px; margin-bottom:50px; border-left: 4px solid #d3d6db;">
<p style = "font-size: 15px; font-weight: bold; margin-left:-20px"><i class="fa fa-arrow-circle-right" style="margin-right: 10px; color: green"></i>SangerAlignment Level</p>
<p style="font-size: 15px; margin-left: 2px; color: gray;">SangerAlignment Level</p>
<p style='font-size: 15px; margin-left: 2px; color: gray;'>SangerRead Level</p>
</div>

```{r echo=FALSE}
library(sangeranalyseR)
```

# Basic Information:
<details class="description"><summary data-open="CLOSE" data-close="MORE DETAILS"></summary>

<ul style="list-style-type:disc;">
  <li>**Output Directory : **  <span class="tab">*`r params$outputDir`*</span></li>

  <li>**Input Parent Directory : **  <span class="tab"><i>`r dirname(params$SangerAlignment@parentDirectory)`</i></span></li>

  <li>**Trimming Method : **  <span class="tab">*`r params$SangerAlignment@contigList[[1]]@forwardReadList[[1]]@QualityReport@TrimmingMethod`*</span></li>
  
  <li>**Forward Reads Suffix Regex : **  <span class="tab">*`r params$SangerAlignment@suffixForwardRegExp`*</span></li>

  <li>**Reverse Reads Suffic Regex : **  <span class="tab">*`r params$SangerAlignment@suffixReverseRegExp`*</span></li>
  
</ul>

</details>

---



<style>
li{
    margin-top: 16px;
}
li:first-child {
    margin-top:0;
}
.tab {position:absolute;left:380px; }

.jexcel_content { 
    height: 60px !important;
}

details.description[open] summary::after {
  content: attr(data-open);
  color: #d45050;
  border-bottom: 2px solid #d45050;
}

details.description:not([open]) summary::after {
  content: attr(data-close);
  color: #4c9c6b;
  border-bottom: 2px solid #4c9c6b;
}

.description {
border-left: 4px solid #d3d6db;
padding-left: 10px;
}
.description summary{
  font-weight: bold;
  font-size: 10px;
  color: #383838;
}
</style>
