test_that("'getProcessors' test", {
    expect_equal(getProcessors(10), 1)
    expect_equal(getProcessors(15), 1)
    expect_equal(getProcessors(2), 1)
    expect_equal(getProcessors(NULL), 1)
})

test_that("'alignContigs' function test", {
    contigList <- sangerAlignment@contigList
    geneticCode <- sangerAlignment@geneticCode
    refAminoAcidSeq <- sangerAlignment@refAminoAcidSeq
    minFractionCallSA <- sangerAlignment@minFractionCallSA
    maxFractionLostSA <- sangerAlignment@maxFractionLostSA
    alignContigs <- alignContigs (contigList, geneticCode,
                                  refAminoAcidSeq, minFractionCallSA,
                                  maxFractionLostSA, 1)
    expect_equal(length(alignContigs$aln), 4)
    expect_equal(as.character(alignContigs$consensus), "TGGTCAACAAATCATAAAGATATTGGAACTYTATAYTTTATTYTRGGCGTCTGAGCAGGAATGGTTGGAGCYGGTATAAGACTYCTAATTCGAATYGAGCTAAGACARCCRGGAGCRTTCCTRGGMAGRGAYCAACTMTAYAATACTATYGTWACTGCWCACGCATTTGTAATAATYTTCTTTCTAGTAATRCCTGTATTYATYGGGGGGTTCGGTAATTGRCTTYTACCTTTAATACTTGGAGCCCCYGAYATRGCATTCCCWCGACTYAACAACATRAGATTCTGACTMCTTCCCCCATCACTRATCCTTYTAGTGTCCTCTGCKGCRGTAGAAAAAGGCGCTGGWACKGGRTGAACTGTTTATCCGCCYCTAGCAAGAAATMTTGCYCAYGCMGGCCCRTCTGTAGAYTTAGCYATYTTTTCYCTTCATTTAGCGGGTGCKTCWTCWATYYTAGGGGCYATTAATTTTATYACYACWGTTATTAAYATGCGWTGAAGAGGMTTACGWCTTGAACGAATYCCMYTRTTYGTYTGAGCYGTRCTAATTACAGTKGTTCTTCTACTYCTATCYTTACCAGTGYTAGCMGGTGCMATTACYATACTWCTTACCGAYCGAAAYCTAAATACCTCCTTCTTTGATCCTGCTGGDGGTGGAGATCCAATCCTATACCAACACTTATTCTGATTTTTTGGTCACCCTGAAGTTTAGGTCATA")
    expect_equal(as.character(alignContigs$aln[[1]]), "------ACAAATCATAAAGATATTGGAACTTTATATTTTATTCTGGGCGTCTGAGCAGGAATGGTTGGAGCCGGTATAAGACTTCTAATTCGAATCGAGCTAAGACAACCAGGAGCGTTCCTGGGCAGAGACCAACTATACAATACTATCGTTACTGCACACGCATTTGTAATAATCTTCTTTCTAGTAATGCCTGTATTCATCGGGKSWKWSSRRRAMTGGYTKTTACCTTTAATACTTGGAGCCCCCGATATAGCATTCCCTCGACTCAACAACATGAGATTCTGACTACTTCCCCCATCACTGATCCTTTTAGTGTCCTCTGCGGCGGTAGAAAAAGGCGCTGGTACGGGGTGAACTGTTTATCCGCCTCTAGCAAGAAATCTTGCCCACGCAGGCCCGTCTGTAGATTTAGCCATCTTTTCCCTTCATTTAGCGGGTGCGTCTTCTATTCTAGGGGCTATTAATTTTATCACCACAGTTATTAATATGCGTTGAAGAGGATTACGTCTTGAACGAATTCCCCTGTTTGTCTGAGCTGTGCTAATTACAGTTGTTCTTCTACTTCTATCTTTACCAGTGCTAGCAGGTGCCATTACCATACTTCTTACCGACCGAAAC------------------------------------------------------------------------------------------------")
    expect_equal(as.character(alignContigs$aln[[2]]), "---------AATCATAAAGATATTGGAACTTTATATTTTATTCTGGGCGTCTGAGCAGGAATGGTTGGAGCCGGTATAAGACTTCTAATTCGAATCGAGCTAAGACAACCAGGAGCGTTCCTGGGCAGAGACCAACTATACAATACTATCGTTACTGCACACGCATTTGTAATAATCTTCTTTCTAGTAATGCCTGTATTCATCGGGGGATTCGGAAACTGGCTTTTACCTTTAATACTTGGAGCCCCCGATATAGCATTCCCTCGACTCAACAACATGAGATTCTGACTACTTCCCCCATCACTGATCCTTTTAGTGTCCTCTGCGGCGGTAGAAAAAGGCGCTGGTACGGGGTGAACTGTTTATCCGCCTCTAGCAAGAAATCTTGCCCACGCAGGCCCGTCTGTAGATTTAGCCATCTTTTCCCTTCATTTAGCGGGTGCGTCTTCTATTCTAGGGGCTATTAATTTTATCACCACAGTTATTAATATGCGTTGAAGAGGATTACGTCTTGAACGAATTCCCCTGTTTGTCTGAGCTGTGCTAATTACAGTTGTTCTTCTACTTCTATCTTTACCAGTGCTAGCAGGTGCCATTACCATACTTCTTACCGACCGAAACCTCAATACTTCATTCTTTGATCCTGCCGGTGGTGGAGACCCCATCCTCTACCAACACTTATTCTGATTTTTTGGTCACCCTGAGGTTTAG------")
    expect_equal(as.character(alignContigs$aln[[3]]), "---TCAACAAATCATAAAGATATTGGAACTCTATACTTTATTTTAGGCGTCTGAGCAGGAATAGTGGGGGCTGGTATAAGACTCCTAATTCGAATTGAGCTAAGACAGCCGGGAGCATTTCTAGGAAGGGATCAACTCTATAACACTATTGTAACTGCTCACGCATTTGTAATAATTTTCTTTCTAGTAATACCTGTATTTATTGGGGGGTTCGGTAATTGACTTCTACCTTTAATACTTGGAGCCCCTGACATGGCATTCCCACGTCTTAACAACATAAGATTTTGACTCCTTCCCCCATCACTAATCCTTCTAGTATCCTCTGCTGCAGTAGAAAAGGGGGCGGGAACTGGATGAACTGTTTATCCGCCCCTAGCAAGAAATATTGCTCATGCCGGCCCATCTGTAGACTTAGCTATTTTTTCTCTTCATTTAGCAGGTGCTTCATCAATCTTGGGTGCCATTAATTTTATTACTACTGTTATTAACATACGATGAAGAGGCTTACGACTTGAGCGAATCCCATTATTCGTTTGAGCCGTACTAATTACAGTGGTCCTTCTACTCTTATCCTTACCAGTATTAGCCGGTGCAATTACTATACTACTTACCGATCGAAATCTAAATACCTCCTTCTTTGATCCTGCTGGAGGTGGAGATCCAATCCTATACCAACACTTATTCTGATTTTTTGGTCACCCTGAAGTNTTAGTCATA")
    expect_equal(as.character(alignContigs$aln[[4]]), "TGGTCAACAAATCATAAAGATATCGGAACTCTATACTTTATTTTAGGCGTCTGAGCAGGAATGGTAGGAGCTGGTATAAGACTCCTAATTCGAATTGAGCTAAGACAGCCGGGAGCATTCCTAGGAAGGGATCAGCTCTATAATACTATTGTAACTGCTCACGCATTTGTAATAATTTTCTTTCTAGTAATACCTGTATTTATTGGGGGGTTCGGTAATTGACTTCTACCTTTAATACTTGGAGCCCCTGACATGGCATTCCCACGACTTAACAACATAAGATTCTGACTCCTTCCCCCGTCACTAATTCTTCTAGTGTCCTCTGCTGCAGTAGAAAAAGGTGCAGGAACTGGATGAACTGTTTATCCGCCCCTAGCAAGAAATATTGCTCATGCCGGCCCATCTGTAGACTTAGCTATTTTTTCTCTTCATTTAGCGGGTGCTTCATCAATCTTAGGGGCCATTAATTTTATTACTACTGTTATTAACATGCGATGAAGAGGCTTACGACTTGAACGAATCCCATTATTCGTTTGAGCCGTACTAATCACAGTGGTGCTTCTACTCCTATCCCTACCAGTGTTAGCCGGTGCAATTACTATATTACTTACCGATCGAAATCTAAATACCTCCTTCTTTGATCCTGCTGGGGGTGGAGATCCAATCCTATATCAACACTTATTCTGATTTTTTGGTCACCCTGAAGTTTAG------")
    expect_equal(length(alignContigs$aln.tree), 4)
})

test_that("'calculateContigSeq' function test", {
    forwardReadList <- sangerContig@forwardReadList
    reverseReadList <- sangerContig@reverseReadList
    refAminoAcidSeq <- sangerContig@refAminoAcidSeq
    minFractionCall <- sangerContig@minFractionCall
    maxFractionLost <- sangerContig@maxFractionLost
    geneticCode <- sangerContig@geneticCode
    acceptStopCodons <- sangerContig@acceptStopCodons
    readingFrame <- sangerContig@readingFrame
    contigSeq <- calculateContigSeq (forwardReadList, reverseReadList,
                                     refAminoAcidSeq, minFractionCall,
                                     maxFractionLost, geneticCode,
                                     acceptStopCodons, readingFrame,
                                     processorsNum)
    expect_equal(as.character(contigSeq$consensusGapfree), "TATATCGACGGCCAGTGGTCAACAAATCATAAAGATATTGGAACTTTATATTTTATTCTGGGCGTCTGAGCAGGAATGGTTGGAGCCGGTATAAGACTTCTAATTCGAATCGAGCTAAGACAACCAGGAGCGTTCCTGGGCAGAGACCAACTATACAATACTATCGTTACTGCACACGCATTTGTAATAATCTTCTTTCTAGTAATGCCTGTATTCATCGGGGGATTCGGAAACTGGCTTTTACCTTTAATACTTGGAGCCCCCGATATAGCATTCCCTCGACTCAACAACATGAGATTCTGACTACTTCCCCCATCACTGATCCTTTTAGTGTCCTCTGCGGCGGTAGAAAAAGGCGCTGGTACGGGGTGAACTGTTTATCCGCCTCTAGCAAGAAATCTTGCCCACGCAGGCCCGTCTGTAGATTTAGCCATCTTTTCCCTTCATTTAGCGGGTGCGTCTTCTATTCTAGGGGCTATTAATTTTATCACCACAGTTATTAATATGCGTTGAAGAGGATTACGTCTTGAACGAATTCCCCTGTTTGTCTGAGCTGTGCTAATTACAGTTGTTCTTCTACTTCTATCTTTACCAGTGCTAGCAGGTGCCATTACCATACTTCTTACCGAC")
    expect_equal(length(contigSeq$aln2), 3)
    expect_equal(as.character(contigSeq$aln2[[1]]), "---------------------------------------------------------CTGGGCGTCTGAGCAGGAATGGTTGGAGCCGGTATAAGACTTCTAATTCGAATCGAGCTAAGACAACCAGGAGCGTTCCTGGGCAGAGACCAACTATACAATACTATCGTTACTGCACACGCATTTGTAATAATCTTCTTTCTAGTAATGCCTGTATTCATCGGGGGATTCGGAAACTGGCTTTTACCTTTAATACTTGGAGCCCCCGATATAGCATTCCCTCGACTCAACAACATGAGATTCTGACTACTTCCCCCATCACTGATCCTTTTAGTGTCCTCTGCGGCGGTAGAAAAAGGCGCTGGTACGGGGTGAACTGTTTATCCGCCTCTAGCAAGAAATCTTGCCCACGCAGGCCCGTCTGTAGATTTAGCCATCTTTTCCCTTCATTTAGCGGGTGCGTCTTCTATTCTAGGGGCTATTAATTTTATCACCACAGTTATTAATATGCGTTGAAGA------------------------------------------------------------------------------------------------------------------")
    expect_equal(as.character(contigSeq$aln2[[2]]), "TATATCGACGGCCAGTGGTCAACAAATCATAAAGATATTGGAACTTTATATTTTATTCTGGGCGTCTGAGCAGGAATGGTTGGAGCCGGTATAAGACTTCTAATTCGAATCGAGCTAAGACAACCAGGAGCGTTCCTGGGCAGAGACCAACTATACAATACTATCGTTACTGCACACGCATTTGTAATAATCTTCTTTCTAGTAATGCCTGTATTCATCGGGGGATTCGGAAACTGGCTTTTACCTTTAATACTTGGAGCCCCCGATATAGCATTCCCTCGACTCAACAACATGAGATTCTGACTACTTCCCCCATCACTGATCCTTTTAGTGTCCTCTGCGGCGGTAGAAAAAGGCGCTGGTACGGGGTGAACTGTTTATCCGCCTCTAGCAAGAAATCTTGCCCACGCAGGCCCGTCTGTAGATTTAGCCATCTTTTCCCTTCATTTAGCGGGTGCGTCTTCTATTCTAGGGGCTATTAATTTTATCACCACAGTTATTAATATGCGTTGAAGAGGATTACGTCTTGAACGAATTCCCCTGTTTGTCTGAGCTGTGCTAATTACAGTTGTTCTTCTACTTCTATCTTTACCAGTGCTAGCAGGTGCCATTACCATACTTCTTACCGAC")
    expect_equal(as.character(contigSeq$aln2[[3]]), "TATATCGACGGCCAGTGGTCAACAAATCATAAAGATATTGGAACTTTATATTTTATTCTGGGCGTCTGAGCAGGAATGGTTGGAGCCGGTATAAGACTTCTAATTCGAATCGAGCTAAGACAACCAGGAGCGTTCCTGGGCAGAGACCAACTATACAATACTATCGTTACTGCACACGCATTTGTAATAATCTTCTTTCTAGTAATGCCTGTATTCATCGGGGGATTCGGAAACTGGCTTTTACCTTTAATACTTGGAGCCCCCGATATAGCATTCCCTCGACTCAACAACATGAGATTCTGACTACTTCCCCCATCACTGATCCTTTTAGTGTCCTCTGCGGCGGTAGAAAAAGGCGCTGGTACGGGGTGAACTGTTTATCCGCCTCTAGCAAGAAATCTTGCCCACGCAGGCCCGTCTGTAGATTTAGCCATCTTTTCCCTTCATTTAGCGGGTGCGTCTTCTATTCTAGGGGCTATTAATTTTATCACCACAGTTATTAATATGCGTTGAAGAGGATTACGTCTTGAACGAATTCCCCTGTTTGTCTGAGCTGTGCTAATTACAGTTGTTCTTCTACTTCTATCTTTACCAGTGCTAGCAGGTGCCATTACCATACTTCTTACCGAC")
})

test_that("'MakeBaseCallsInside' function test - forward", {
    traceMatrixF <- sangerRead@traceMatrix
    peakPosMatrixRawF <- sangerRead@peakPosMatrixRaw
    qualityPhredScoresRawF <- sangerRead@QualityReport@qualityPhredScoresRaw
    signalRatioCutoffF <- sangerRead@ChromatogramParam@signalRatioCutoff
    readFeatureF <- sangerRead@readFeature
    baseCallRes <- MakeBaseCallsInside (traceMatrixF, peakPosMatrixRawF,
                                        qualityPhredScoresRawF,
                                        signalRatioCutoffF, readFeatureF)
    expect_equal(length(baseCallRes$primarySeq), length(sangerRead@primarySeq))
    expect_equal(length(baseCallRes$secondarySeq), length(sangerRead@secondarySeq))
    expect_equal(as.character(baseCallRes$primarySeq), "CACTTTATATTTTATTCTGGGCGTCTGAGCAGGAATGGTTGGAGCCGGTATAAGACTTCTAATTCGAATCGAGCTAAGACAACCAGGAGCGTTCCTGGGCAGAGACCAACTATACAATACTATCGTTACTGCACACGCATTTGTAATAATCTTCTTTCTAGTAATGCCTGTATTCATCGGGGGATTCGGAAACTGGCTTTTACCTTTAATACTTGGAGCCCCCGATATAGCATTCCCTCGACTCAACAACATGAGATTCTGACTACTTCCCCCATCACTGATCCTTTTAGTGTCCTCTGCGGCGGTAGAAAAAGGCGCTGGTACGGGGTGAACTGTTTATCCGCCTCTAGCAAGAAATCTTGCCCACGCAGGCCCGTCTGTAGATTTAGCCATCTTTTCCCTTCATTTAGCGGGTGCGTCTTCTATTCTAGGGGCTATTAATTTTATCACCACAGTTATTAATATGCGTTGAAGAGGATTACGTCTTGAACGAATTCCCCTGTTTGTCTGAGCTGTGCTAATTACAGTTGTTCTTCTACTTCTATCTTTACCAGTGCTAGCAGGTGCCATTACCATACTTCTTACCGACCGAAACCTCAATACTTCATTCTTTGATCCTGCCGGTGGTGGAGACCCCATCCTCTACTAGCACTTATTCTGATTTTTAGATCACCCTGATGTTGAGTCATACTGAATTCCTGA")
    expect_equal(as.character(baseCallRes$secondarySeq), "TACTTTATATTTTATTCTGGGCGTCTGAGCAGGAATGGTTGGAGCCGGTATAAGACTTCTAATTCGAATCGAGCTAAGACAACCAGGAGCGTTCCTGGGCAGAGACCAACTATACAATACTATCGTTACTGCACACGCATTTGTAATAATCTTCTTTCTAGTAATGCCTGTATTCATCGGGGGATTCGGAAACTGGCTTTTACCTTTAATACTTGGAGCCCCCGATATAGCATTCCCTCGACTCAACAACATGAGATTCTGACTACTTCCCCCATCACTGATCCTTTTAGTGTCCTCTGCGGCGGTAGAAAAAGGCGCTGGTACGGGGTGAACTGTTTATCCGCCTCTAGCAAGAAATCTTGCCCACGCAGGCCCGTCTGTAGATTTAGCCATCTTTTCCCTTCATTTAGCGGGTGCGTCTTCTATTCTAGGGGCTATTAATTTTATCACCACAGTTATTAATATGCGTTGAAGAGGATTACGTCTTGAACGAATTCCCCTGTTTGTCTGAGCTGTGCTAATTACAGTTGTTCTTCTACTTCTATCTTTACCAGTGCTAGCAGGTGCCATTACCATACTTCTTACCGACCGAAACCTCAATACTTCATTCTTTGATCCTGCCGGTGGTGGAGACCCCATCCTCTACTAGCACTTATTCTGATTTTTCGATCACCCTGATGTTGAGTCATAGTGAATTCCTGA")
})

test_that("'MakeBaseCallsInside' function test - reverse", {
    traceMatrixR <- sangerReadR@traceMatrix
    peakPosMatrixRawR <- sangerReadR@peakPosMatrixRaw
    qualityPhredScoresRawR <- sangerReadR@QualityReport@qualityPhredScoresRaw
    signalRatioCutoffR <- sangerReadR@ChromatogramParam@signalRatioCutoff
    readFeatureR <- sangerReadR@readFeature
    baseCallRes <- MakeBaseCallsInside (traceMatrixR, peakPosMatrixRawR,
                                        qualityPhredScoresRawR,
                                        signalRatioCutoffR, readFeatureR)
    expect_equal(length(baseCallRes$primarySeq), length(sangerReadR@primarySeq))
    expect_equal(length(baseCallRes$secondarySeq), length(sangerReadR@secondarySeq))
    expect_equal(as.character(baseCallRes$primarySeq), "CCGTAGTAGGTGTTGGTAGAGGATGGGGTCTCCACCACCGGCAGGATCAAAGAATGAAGTATTGAGGTTTCGGTCGGTAAGAAGTATGGTAATGGCACCTGCTAGCACTGGTAAAGATAGAAGTAGAAGAACAACTGTAATTAGCACAGCTCAGACAAACAGGGGAATTCGTTCAAGACGTAATCCTCTTCAACGCATATTAATAACTGTGGTGATAAAATTAATAGCCCCTAGAATAGAAGACGCACCCGCTAAATGAAGGGAAAAGATGGCTAAATCTACAGACGGGCCTGCGTGGGCAAGATTTCTTGCTAGAGGCGGATAAACAGTTCACCCCGTACCAGCGCCTTTTTCTACCGCCGCAGAGGACACTAAAAGGATCAGTGATGGGGGAAGTAGTCAGAATCTCATGTTGTTGAGTCGAGGGAATGCTATATCGGGGGCTCCAAGTATTAAAGGTAAAAGCCAGTTTCCGAATCCCCCGATGAATACAGGCATTACTAGAAAGAAGATTATTACAAATGCGTGTGCAGTAACGATAGTATTGTATAGTTGGTCTCTGCCCAGGAACGCTCCTGGTTGTCTTAGCTCGATTCGAATTAGAAGTCTTATACCGGCTCCAACCATTCCTGCTCAGACGCCCAGAATAAAATATAAAGTTCCAATATCTTTATGATTTGTTGACCACTGGCCGTCGATATACAA")
    expect_equal(as.character(baseCallRes$secondarySeq), "CAGCAGTAGGTGTTGGTAGAGGATGGGGTCTCCACCACCGGCAGGATCAAAGAATGAAGTATTGCGGTTTCGGTCGGTAAGAAGTATGGTAATGGCACCTGCTAGCACTGGTAAAGATAGAAGTAGAAGAACAACTGTAATTAGCACAGCTCAGACAAACAGGGGAATTCGTTCAAGACGTAATCCTCTTCAACGCATATTAATAACTGTGGTGATAAAATTAATAGCCCCTAGAATAGAAGACGCACCCGCTAAATGAAGGGAAAAGATGGCTAAATCTACAGACGGGCCTGCGTGGGCAAGATTTCTTGCTAGAGGCGGATAAACAGTTCACCCCGTACCAGCGCCTTTTTCTACCGCCGCAGAGGACACTAAAAGGATCAGTGATGGGGGAAGTAGTCAGAATCTCATGTTGTTGAGTCGAGGGAATGCTATATCGGGGGCTCCAAGTATTAAAGGTAAAAGCCAGTTTCCGAATCCCCCGATGAATACAGGCATTACTAGAAAGAAGATTATTACAAATGCGTGTGCAGTAACGATAGTATTGTATAGTTGGTCTCTGCCCAGGAACGCTCCTGGTTGTCTTAGCTCGATTCGAATTAGAAGTCTTATACCGGCTCCAACCATTCCTGCTCAGACGCCCAGAATAAAATATAAAGTTCCAATATCTTTATGATTTGTTGACCACTGGCCGTCGATGTACAA")
})

test_that("'M1inside_calculate_trimming' function test 1", {
    qualityPhredScores <- sangerRead@QualityReport@qualityPhredScores
    qualityBaseScores <- sangerRead@QualityReport@qualityBaseScores
    M1TrimmingCutoff <- sangerRead@QualityReport@M1TrimmingCutoff
    m1Trimming <- M1inside_calculate_trimming(qualityPhredScores,
                                              qualityBaseScores,
                                              0.0001)
    expect_equal(m1Trimming[["rawSeqLength"]], 702)
    expect_equal(m1Trimming[["rawMeanQualityScore"]], 52.87607, , tolerance=1e-6)
    expect_equal(m1Trimming[["rawMinQualityScore"]], 1)
    expect_equal(m1Trimming[["trimmedStartPos"]], 16)
    expect_equal(m1Trimming[["trimmedFinishPos"]], 477)
    expect_equal(m1Trimming[["trimmedSeqLength"]], 461)
    expect_equal(m1Trimming[["trimmedMeanQualityScore"]], 58.21041, tolerance=1e-6)
    expect_equal(m1Trimming[["trimmedMinQualityScore"]], 13)
    expect_equal(m1Trimming[["remainingRatio"]], 0.6566952, tolerance=1e-6)
})


test_that("'M1inside_calculate_trimming' function test 2", {
    qualityPhredScores <- sangerRead@QualityReport@qualityPhredScores
    qualityBaseScores <- sangerRead@QualityReport@qualityBaseScores
    M1TrimmingCutoff <- sangerRead@QualityReport@M1TrimmingCutoff
    m1Trimming <- M1inside_calculate_trimming(qualityPhredScores,
                                              qualityBaseScores,
                                              0.01)
    expect_equal(m1Trimming[["rawSeqLength"]], 702)
    expect_equal(m1Trimming[["rawMeanQualityScore"]], 52.87607, , tolerance=1e-6)
    expect_equal(m1Trimming[["rawMinQualityScore"]], 1)
    expect_equal(m1Trimming[["trimmedStartPos"]], 8)
    expect_equal(m1Trimming[["trimmedFinishPos"]], 679)
    expect_equal(m1Trimming[["trimmedSeqLength"]], 671)
    expect_equal(m1Trimming[["trimmedMeanQualityScore"]], 54.48286, tolerance=1e-6)
    expect_equal(m1Trimming[["trimmedMinQualityScore"]], 8)
    expect_equal(m1Trimming[["remainingRatio"]], 0.9558405, tolerance=1e-6)
})

test_that("'M1inside_calculate_trimming' function test 3", {
    qualityPhredScores <- sangerRead@QualityReport@qualityPhredScores
    qualityBaseScores <- sangerRead@QualityReport@qualityBaseScores
    M1TrimmingCutoff <- sangerRead@QualityReport@M1TrimmingCutoff
    m1Trimming <- M1inside_calculate_trimming(qualityPhredScores,
                                              qualityBaseScores,
                                              1)
    expect_equal(m1Trimming[["rawSeqLength"]], 702)
    expect_equal(m1Trimming[["rawMeanQualityScore"]], 52.87607, , tolerance=1e-6)
    expect_equal(m1Trimming[["rawMinQualityScore"]], 1)
    expect_equal(m1Trimming[["trimmedStartPos"]], 1)
    expect_equal(m1Trimming[["trimmedFinishPos"]], 702)
    expect_equal(m1Trimming[["trimmedSeqLength"]], 701)
    expect_equal(m1Trimming[["trimmedMeanQualityScore"]], 52.94864, tolerance=1e-6)
    expect_equal(m1Trimming[["trimmedMinQualityScore"]], 1)
    expect_equal(m1Trimming[["remainingRatio"]], 0.9985755, tolerance=1e-6)
})

test_that("'M1inside_calculate_trimming' function test 4", {
    qualityPhredScores <- sangerRead@QualityReport@qualityPhredScores
    qualityBaseScores <- sangerRead@QualityReport@qualityBaseScores
    M1TrimmingCutoff <- sangerRead@QualityReport@M1TrimmingCutoff
    m1Trimming <- M1inside_calculate_trimming(qualityPhredScores,
                                              qualityBaseScores,
                                              0)
    expect_equal(m1Trimming[["rawSeqLength"]], 702)
    expect_equal(m1Trimming[["rawMeanQualityScore"]], 52.87607, , tolerance=1e-6)
    expect_equal(m1Trimming[["rawMinQualityScore"]], 1)
    expect_equal(m1Trimming[["trimmedStartPos"]], 1)
    expect_equal(m1Trimming[["trimmedFinishPos"]], 2)
    expect_equal(m1Trimming[["trimmedSeqLength"]], 1)
    expect_equal(m1Trimming[["trimmedMeanQualityScore"]], 4, tolerance=1e-6)
    expect_equal(m1Trimming[["trimmedMinQualityScore"]], 4)
    expect_equal(m1Trimming[["remainingRatio"]], 0.001424501, tolerance=1e-6)
})

test_that("'M2inside_calculate_trimming' function test 1", {
    qualityPhredScores <- sangerRead@QualityReport@qualityPhredScores
    m2Trimming <- M2inside_calculate_trimming(qualityPhredScores,
                                              40,
                                              14)

    expect_equal(m2Trimming[["rawSeqLength"]], 702)
    expect_equal(m2Trimming[["rawMeanQualityScore"]], 52.87607, , tolerance=1e-6)
    expect_equal(m2Trimming[["rawMinQualityScore"]], 1)
    expect_equal(m2Trimming[["trimmedStartPos"]], 21)
    expect_equal(m2Trimming[["trimmedFinishPos"]], 650)
    expect_equal(m2Trimming[["trimmedSeqLength"]], 629)
    expect_equal(m2Trimming[["trimmedMeanQualityScore"]], 55.80445, tolerance=1e-6)
    expect_equal(m2Trimming[["trimmedMinQualityScore"]], 15)
    expect_equal(m2Trimming[["remainingRatio"]], 0.8960114, tolerance=1e-6)
})

test_that("'M2inside_calculate_trimming' function test 2", {
    qualityPhredScores <- sangerRead@QualityReport@qualityPhredScores
    m2Trimming <- M2inside_calculate_trimming(qualityPhredScores,
                                              45,
                                              12)

    expect_equal(m2Trimming[["rawSeqLength"]], 702)
    expect_equal(m2Trimming[["rawMeanQualityScore"]], 52.87607, , tolerance=1e-6)
    expect_equal(m2Trimming[["rawMinQualityScore"]], 1)
    expect_equal(m2Trimming[["trimmedStartPos"]], 37)
    expect_equal(m2Trimming[["trimmedFinishPos"]], 573)
    expect_equal(m2Trimming[["trimmedSeqLength"]], 536)
    expect_equal(m2Trimming[["trimmedMeanQualityScore"]], 57.6791, tolerance=1e-6)
    expect_equal(m2Trimming[["trimmedMinQualityScore"]], 19)
    expect_equal(m2Trimming[["remainingRatio"]], 0.7635328, tolerance=1e-6)
})

