test_that("SangerRead - FASTA Initial test", {
    expect_type(sangerReadFa, "S4")
    expect_s4_class(sangerReadFa, "SangerRead")
    expect_equal(sangerReadFa@readFeature, "Forward Read")
    expect_equal(basename(sangerReadFa@readFileName), "ACHLO006-09[LCO1490_t1,HCO2198_t1]_F_1.fa")
    expect_equal(as.character(sangerReadFa@primarySeq), "CACTTTATATTTTATTCTGGGCGTCTGAGCAGGAATGGTTGGAGCCGGTATAAGACTTCTAATTCGAATCGAGCTAAGACAACCAGGAGCGTTCCTGGGCAGAGACCAACTATACAATACTATCGTTACTGCACACGCATTTGTAATAATCTTCTTTCTAGTAATGCCTGTATTCATCGGGGGATTCGGAAACTGGCTTTTACCTTTAATACTTGGAGCCCCCGATATAGCATTCCCTCGACTCAACAACATGAGATTCTGACTACTTCCCCCATCACTGATCCTTTTAGTGTCCTCTGCGGCGGTAGAAAAAGGCGCTGGTACGGGGTGAACTGTTTATCCGCCTCTAGCAAGAAATCTTGCCCACGCAGGCCCGTCTGTAGATTTAGCCATCTTTTCCCTTCATTTAGCGGGTGCGTCTTCTATTCTAGGGGCTATTAATTTTATCACCACAGTTATTAATATGCGTTGAAGAGGATTACGTCTTGAACGAATTCCCCTGTTTGTCTGAGCTGTGCTAATTACAGTTGTTCTTCTACTTCTATCTTTACCAGTGCTAGCAGGTGCCATTACCATACTTCTTACCGACCGAAACCTCAATACTTCATTCTTTGATCCTGCCGGTGGTGGAGACCCCATCCTCTACTAGCACTTATTCTGATTTTTAGATCACCCTGATGTTGAGTCATACTGAATTCCTGA")
    expect_equal(as.character(sangerReadFa@secondarySeq), "")
    expect_equal(as.character(sangerReadFa@primaryAASeqS1), "HFIFYSGRLSRNGWSRYKTSNSNRAKTTRSVPGQRPTIQYYRYCTRICNNLLSSNACIHRGIRKLAFTFNTWSPRYSIPSTQQHEILTTSPITDPFSVLCGGRKRRWYGVNCLSASSKKSCPRRPVCRFSHLFPSFSGCVFYSRGY*FYHHSY*YALKRITS*TNSPVCLSCANYSCSSTSIFTSASRCHYHTSYRPKPQYFIL*SCRWWRPHPLLALILIFRSP*C*VILNS*")
    expect_equal(as.character(sangerReadFa@primaryAASeqS2), "TLYFILGV*AGMVGAGIRLLIRIELRQPGAFLGRDQLYNTIVTAHAFVIIFFLVMPVFIGGFGNWLLPLILGAPDIAFPRLNNMRF*LLPPSLILLVSSAAVEKGAGTG*TVYPPLARNLAHAGPSVDLAIFSLHLAGASSILGAINFITTVINMR*RGLRLERIPLFV*AVLITVVLLLLSLPVLAGAITILLTDRNLNTSFFDPAGGGDPILY*HLF*FLDHPDVESY*IP")
    expect_equal(as.character(sangerReadFa@primaryAASeqS3), "LYILFWASEQEWLEPV*DF*FESS*DNQERSWAETNYTILSLLHTHL**SSF**CLYSSGDSETGFYL*YLEPPI*HSLDSTT*DSDYFPHH*SF*CPLRR*KKALVRGELFIRL*QEILPTQARL*I*PSFPFI*RVRLLF*GLLILSPQLLICVEEDYVLNEFPCLSELC*LQLFFYFYLYQC*QVPLPYFLPTETSILHSLILPVVETPSSTSTYSDF*ITLMLSHTEFL")
    expect_equal(is.null(sangerReadFa@ChromatogramParam), TRUE)
    expect_equal(is.null(sangerReadFa@QualityReport), TRUE)
    expect_equal(is.null(sangerReadFa@abifRawData), TRUE)
    expect_equal(as.character(sangerReadFa@primarySeqRaw), "")
    expect_equal(as.character(sangerReadFa@secondarySeqRaw), "")
    expect_equal(sangerReadFa@primarySeqID, "From fasta file")
    expect_equal(sangerReadFa@secondarySeqID, "")
    expect_equal(sangerReadFa@traceMatrix, matrix())
    expect_equal(sangerReadFa@peakPosMatrix, matrix())
    expect_equal(sangerReadFa@peakAmpMatrix, matrix())
})

test_that("SangerRead - FASTA functions test", {
    expect_message(qualityBasePlot(sangerReadFa),
                 paste("SangerRead with 'FASTA' inputSource",
                       "cannot plot quality plots"))
    expect_message(updateQualityParam(sangerReadFa),
                 paste("SangerRead with 'FASTA' inputSource",
                 "cannot update quality parameters"))
    expect_message(MakeBaseCalls(sangerReadFa),
                 paste("SangerRead with 'FASTA'",
                       "inputSource cannot do base calling"))

    outputFasta <- writeFastaSR(sangerReadFa)
    expect_true(file.exists(outputFasta))
    con = file(outputFasta, "r")
    line = readLines(con, n = 1)
    expect_equal(line, ">ACHLO006-09[LCO1490_t1,HCO2198_t1]_F_1.fa")
    line = readLines(con, n = 1)
    expect_equal(line, "CACTTTATATTTTATTCTGGGCGTCTGAGCAGGAATGGTTGGAGCCGGTATAAGACTTCTAATTCGAATCGAGCTAAGAC")
    line = readLines(con, n = 1)
    expect_equal(line, "AACCAGGAGCGTTCCTGGGCAGAGACCAACTATACAATACTATCGTTACTGCACACGCATTTGTAATAATCTTCTTTCTA")
    line = readLines(con, n = 1)
    expect_equal(line, "GTAATGCCTGTATTCATCGGGGGATTCGGAAACTGGCTTTTACCTTTAATACTTGGAGCCCCCGATATAGCATTCCCTCG")
    line = readLines(con, n = 1)
    expect_equal(line, "ACTCAACAACATGAGATTCTGACTACTTCCCCCATCACTGATCCTTTTAGTGTCCTCTGCGGCGGTAGAAAAAGGCGCTG")
    line = readLines(con, n = 1)
    expect_equal(line, "GTACGGGGTGAACTGTTTATCCGCCTCTAGCAAGAAATCTTGCCCACGCAGGCCCGTCTGTAGATTTAGCCATCTTTTCC")
    line = readLines(con, n = 1)
    expect_equal(line, "CTTCATTTAGCGGGTGCGTCTTCTATTCTAGGGGCTATTAATTTTATCACCACAGTTATTAATATGCGTTGAAGAGGATT")
    line = readLines(con, n = 1)
    expect_equal(line, "ACGTCTTGAACGAATTCCCCTGTTTGTCTGAGCTGTGCTAATTACAGTTGTTCTTCTACTTCTATCTTTACCAGTGCTAG")
    line = readLines(con, n = 1)
    expect_equal(line, "CAGGTGCCATTACCATACTTCTTACCGACCGAAACCTCAATACTTCATTCTTTGATCCTGCCGGTGGTGGAGACCCCATC")
    line = readLines(con, n = 1)
    expect_equal(line, "CTCTACTAGCACTTATTCTGATTTTTAGATCACCCTGATGTTGAGTCATACTGAATTCCTGA")
    close(con)
    unlink(outputFasta)
})
