test_that("SangerRead writeFasta SR", {
    outputFasta <- writeFastaSR(sangerRead)
    expect_true(file.exists(outputFasta))
    con = file(outputFasta, "r")
    line = readLines(con, n = 1)
    expect_equal(line, ">ACHLO006-09[LCO1490_t1,HCO2198_t1]_F_1.ab1")
    line = readLines(con, n = 1)
    expect_equal(line, "CACTTTATATTTTATTCTGGGCGTCTGAGCAGGAATGGTTGGAGCCGGTATAAGACTTCTAATTCGAATCGAGCTAAGAC")
    line = readLines(con, n = 1)
    expect_equal(line, "AACCAGGAGCGTTCCTGGGCAGAGACCAACTATACAATACTATCGTTACTGCACACGCATTTGTAATAATCTTCTTTCTA")
    line = readLines(con, n = 1)
    expect_equal(line, "GTAATGCCTGTATTCATCGGGGGATTCGGAAACTGGCTTTTACCTTTAATACTTGGAGCCCCCGATATAGCATTCCCTCG")
    line = readLines(con, n = 1)
    expect_equal(line, "ACTCAACAACATGAGATTCTGACTACTTCCCCCATCACTGATCCTTTTAGTGTCCTCTGCGGCGGTAGAAAAAGGCGCTG")
    line = readLines(con, n = 1)
    expect_equal(line, "GTACGGGGTGAACTGTTTATCCGCCTCTAGCAAGAAATCTTGCCCACGCAGGCCCGTCTGTAGATTTAGCCATCTTTTCC")
    line = readLines(con, n = 1)
    expect_equal(line, "CTTCATTTAGCGGGTGCGTCTTCTATTCTAGGGGCTATTAATTTTATCACCACAGTTATTAATATGCGTTGAAGAGGATT")
    line = readLines(con, n = 1)
    expect_equal(line, "ACGTCTTGAACGAATTCCCCTGTTTGTCTGAGCTGTGCTAATTACAGTTGTTCTTCTACTTCTATCTTTACCAGTGCTAG")
    line = readLines(con, n = 1)
    expect_equal(line, "CAGGTGCCATTACCATACTTCTTACCGACCGAAACCTCAATACTTCATTCTTTGATCCTGCCGGTGGTGGAGACCCCATC")
    line = readLines(con, n = 1)
    expect_equal(line, "CTCTACTAGCACTTATTCTGATTTTTAGATCACCCTGATGTTGAGTCATACTGAATTCCTGA")
    close(con)
    unlink(outputFasta)
})
