// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// peakvalues_cpp
Rcpp::NumericVector peakvalues_cpp(Rcpp::NumericMatrix x, double pstart, double pstop);
RcppExport SEXP _sangeranalyseR_peakvalues_cpp(SEXP xSEXP, SEXP pstartSEXP, SEXP pstopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type pstart(pstartSEXP);
    Rcpp::traits::input_parameter< double >::type pstop(pstopSEXP);
    rcpp_result_gen = Rcpp::wrap(peakvalues_cpp(x, pstart, pstop));
    return rcpp_result_gen;
END_RCPP
}
// peakvalues_batch_cpp
Rcpp::NumericMatrix peakvalues_batch_cpp(Rcpp::NumericMatrix x, Rcpp::NumericVector pstarts, Rcpp::NumericVector pstops);
RcppExport SEXP _sangeranalyseR_peakvalues_batch_cpp(SEXP xSEXP, SEXP pstartsSEXP, SEXP pstopsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pstarts(pstartsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pstops(pstopsSEXP);
    rcpp_result_gen = Rcpp::wrap(peakvalues_batch_cpp(x, pstarts, pstops));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sangeranalyseR_peakvalues_cpp", (DL_FUNC) &_sangeranalyseR_peakvalues_cpp, 3},
    {"_sangeranalyseR_peakvalues_batch_cpp", (DL_FUNC) &_sangeranalyseR_peakvalues_batch_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sangeranalyseR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
