# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

peakvalues_cpp <- function(x, pstart, pstop) {
    .Call(`_sangeranalyseR_peakvalues_cpp`, x, pstart, pstop)
}

peakvalues_batch_cpp <- function(x, pstarts, pstops) {
    .Call(`_sangeranalyseR_peakvalues_batch_cpp`, x, pstarts, pstops)
}

